buildscript {
    repositories {
        maven { url = 'https://maven.fabricmc.net/' }
        mavenCentral()
        gradlePluginPortal()
        maven { url = 'https://jitpack.io' }
    }
    dependencies {
        classpath 'net.fabricmc:fabric-loom:1.7-SNAPSHOT'
        classpath 'com.gradleup.shadow:shadow-gradle-plugin:8.3.5'
    }
}

apply plugin: 'net.fabricmc.fabric-loom'
apply plugin: 'com.gradleup.shadow'
apply plugin: 'maven-publish'

version = project.mod_version
group = project.maven_group

base {
    archivesName = project.archives_base_name
}

repositories {
    maven { url = 'https://maven.fabricmc.net/' }
    maven {
        url = 'https://pkgs.dev.azure.com/djtheredstoner/DevAuth/_packaging/devauth/maven/v1'
        content {
            includeGroup "no.djtheredstoner"
        }
    }
    maven {
        url = 'https://maven.isxander.dev/releases'
        content {
            includeGroup "dev.isxander"
        }
    }
    maven {
        url = 'https://cursemaven.com'
        content {
            includeGroup "curse.maven"
        }
    }
    mavenCentral()
}

loom {
    accessWidenerPath = file("src/main/resources/flashback.accesswidener")
}

dependencies {
    // Minecraft and Fabric
    minecraft "com.mojang:minecraft:${project.minecraft_version}"
    mappings "net.fabricmc:yarn:${project.minecraft_version}+build.1:v2"
    modImplementation "net.fabricmc:fabric-loader:${project.loader_version}"
    modImplementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_version}"

    // Mod menu & DevAuth
    modRuntimeOnly("no.djtheredstoner:devauth-fabric:1.1.2")

    // Dependencies
    includeImplementation("com.moulberry:flashback-common:1.0.0")
    
    // Apache stuff
    includeImplementation('commons-io:commons-io:2.11.0')
    includeImplementation('org.apache.httpcomponents:httpclient:4.5.14')
    includeImplementation('org.apache.httpcomponents:httpmime:4.5.14')

    // Mod compatibility
    compileOnly('maven.modrinth:distant-horizons:2.1.2-a')
    compileOnly('maven.modrinth:sodium:mc1.21-0.5.11')
    compileOnly('maven.modrinth:iris:1.7.2+1.21')
    compileOnly('maven.modrinth:replaymod:1.21-2.6.16')
    compileOnly('maven.modrinth:simple-voice-chat:fabric-1.21-2.5.18')
    compileOnly('maven.modrinth:modmenu:11.0.0')
    compileOnly('maven.modrinth:vulkanmod:0.4.5')

    // Native libs for Android packaging
    shadow(implementation(name: 'ffmpeg-legacy-android-arm64-v8a', ext: 'jar'))
    shadow(fileTree(dir: 'libs', include: ['*.jar']))
}

processResources {
    inputs.property "version", project.version

    filesMatching("fabric.mod.json") {
        expand "version": project.version
    }
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
    sourceCompatibility = JavaVersion.VERSION_21
    targetCompatibility = JavaVersion.VERSION_21
}

tasks.withType(JavaCompile).configureEach {
    options.release = 21
}

tasks.named('jar', Jar) {
    classifier = 'thin'
}

shadowJar {
    configurations = [project.configurations.shadow]
    archiveClassifier = 'flashback'
    destinationDirectory = file("${buildDir}/libs")
    
    exclude 'META-INF/**'
    exclude 'LICENSE.txt'
}

tasks.register('mergeShadowWithUnclassified', Jar) {
    archiveBaseName = 'output'
    archiveVersion = project.version
    from(zipTree(shadowJar.archiveFile))
    from(zipTree(jar.archiveFile))
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE

    var archiveFileFrom = archiveFile
    archiveFile.set(provider { archiveFileFrom.get() })
}

project.assemble.dependsOn(mergeShadowWithUnclassified)
